environments:
  local:
    executor: local
    path_style: windows
    git_remote_url: "https://github.com/josephweaver/research-etl.git"
    modules: [ "Python/3.11.3-GCCcore-12.3.0" ]
    rclone_bin: "bin/rclone"
    basedir: "{global.basedir}"
    workdir: "{basedir}/work"
    logdir: "{basedir}/logs"
    datadir: "{basedir}/data"
    tmpdir: "{basedir}/tmp"
    artifactsdir: "{basedir}/artifacts"


  hpcc_msu:
    executor: slurm
    path_style: unix
    git_remote_url: "git@github.com:josephweaver/research-etl.git"
    host: hpcc.msu.edu
    rclone_bin: "rclone"
    # partition: scavenger # optional: specify valid
    # account: weave151  # optional: specify valid allocation if required
    time: "01:00:00"
    cpus_per_task: 2
    mem: "8G"

    modules: [ "Python/3.11.3-GCCcore-12.3.0", "rclone/1.63.1-amd64"]
    job_limit: 1000
    array_task_limit: 1000
    max_parallel: 50
    ssh_timeout: 120
    scp_timeout: 300
    ssh_retries: 2
    scp_retries: 2
    remote_retry_delay_seconds: 2
    ssh_connect_timeout: 20
    ssh_strict_host_key_checking: accept-new
    ssh_host: dev-amd24.passwordless
    ssh_user: weave151
    basedir: /mnt/scratch/weave151
    remote_repo: "{basedir}/etl"
    workdir: "{basedir}/work"
    logdir: "{workdir}/logs"
    db_sync_queue_dir: "{workdir}/db_sync_queue/pending"
    propagate_db_secret: false
    load_secrets_file: false
    sync: true

  hpcc_msu_direct:
    executor: hpcc_direct
    path_style: unix
    git_remote_url: "git@github.com:josephweaver/research-etl.git"
    rclone_bin: "rclone"
    modules: [ "Python/3.11.3-GCCcore-12.3.0", "rclone/1.63.1-amd64"]
    ssh_timeout: 120
    ssh_host: dev-amd24.passwordless
    ssh_user: weave151
    basedir: /mnt/scratch/weave151
    remote_repo: "{basedir}/etl"
    workdir: "{basedir}/work"
    logdir: "{workdir}/logs"
    db_sync_queue_dir: "{workdir}/db_sync_queue/pending"
